version: 2.1
jobs:
  build:
      docker:
        - image: circleci/python
      steps:
        - checkout
        - run: ls
        - run: tar -cf ourcode.tar ./main.py
        - run: ls
        - run: pwd
        - persist_to_workspace:
            root: .
            paths:
              - ourcode.tar
  deploy:
    docker:
      - image: circleci/python
    steps:
      - attach_workspace:
          at: .
      - run: ls
      - add_ssh_keys:
         fingerprints:
           - "1b:b7:f0:68:bc:10:62:e2:2a:8e:3d:da:bb:15:4a:e6"
      - run:  ssh  -o StrictHostKeyChecking=no ubuntu@ec2-18-206-40-133.compute-1.amazonaws.com "pwd "
      - run:  scp -o StrictHostKeyChecking=no ourcode.tar  ubuntu@ec2-18-206-40-133.compute-1.amazonaws.com:/home/ubuntu
      - run:  ssh  -o StrictHostKeyChecking=no ubuntu@ec2-18-206-40-133.compute-1.amazonaws.com "ls -al"



workflows:
  version: 2
  akin-pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build